### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Bedrock16** [SealedSaucer/Fake-Streamer#1]
Can I make my account with activities like playing , watching ?

**Comment by SealedSaucer** [comment]
Yeah, You have to know some basic knowledge of node.js for this tho...

Try removing the `url` and change the `type` to `WATCHING` or `PLAYING`

**Comment by Bedrock16** [comment]
I will try this (actually trying right now) and will tell you the conclusion

**Comment by SealedSaucer** [comment]
Let me know if it worked 👍

**Comment by Bedrock16** [comment]
I will try to add text too (I will do it later)

**Comment by Bedrock16** [comment]
It's working

**Comment by SealedSaucer** [comment]
Great!

Feel free to Star and Fork the Repo ;)

**Comment by Bedrock16** [comment]
Done bro .... And too can update it ..... It will be helpful 
I also dmed you on Discord Atharv Pathak#0001

**Comment by SealedSaucer** [comment]
Sure! ❤️
